### PR TITLE
Remove lucene hint

### PR DESCRIPTION
**Pull request by myoung34**
The text is more annoying than it is helpful. On long queries it actually just gets in the way and prevents me from reading/highlighting/modifying text

### CODE REVIEW

**Comment by sivasamyk** [comment]
@myoung34 When there is data in the search field, the lucene hint should be hidden. Do you still see the link when there is text in search field?

**Comment by myoung34** [comment]
Big time

**Comment by myoung34** [comment]
Browser: firefox 58.0 (64-bit) on ubuntu
Logtrail: `/usr/share/kibana/bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.21/logtrail-5.6.2-0.1.21.zip`

**Comment by sivasamyk** [comment]
Ah. Have added hiding of lucene hint option in logtrail v 0.1.23 as fix for #195 

I see you are using Kibana 5.6.2. Follow these steps:

1) Download th logtrail zip from https://github.com/sivasamyk/logtrail/releases/download/v0.1.23/logtrail-5.6.3-0.1.23.zip
2) Unzip the contents and change kibana.version to 5.6.2 in package.json
3) zip it back. Now you can install this in Kibana 5.6.2

.

**Comment by myoung34** [comment]
I plan on upgrading to 6.1 soon so I'll include that fix in there. Thanks!

**Pull request closed without merging**
